package coarsermi;

/**
 * Defines an observer used to collect the
 * connection failures and errors. This interface is used to separate the
 * interests of the users of the stubs from those of the objects that manage the
 * remote communication
 * 
 * @author Salvatore Giampa'
 *
 */
public interface FailureObserver {
	/**
	 * Called when a non reliable exception was generated by the specified, although disposed, {@link ObjectPeer} object.
	 * @param objectPeer the disposed {@link ObjectPeer} object
	 * @param exception the thrown exception
	 */
	void failure(ObjectPeer objectPeer, Exception exception);
}
